/**
 */
package unified.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ViewerNotification;

import unified.FMEAItem;
import unified.UnifiedPackage;

/**
 * This is the item provider adapter for a {@link unified.FMEAItem} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FMEAItemItemProvider extends UnifiedElementItemProvider {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FMEAItemItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addSeverityPropertyDescriptor(object);
			addOccurrencePropertyDescriptor(object);
			addDetectionPropertyDescriptor(object);
			addLocalEffectPropertyDescriptor(object);
			addSystemEffectPropertyDescriptor(object);
			addRecommendedActionPropertyDescriptor(object);
			addActionStatusPropertyDescriptor(object);
			addFailureModePropertyDescriptor(object);
			addAnalyzedComponentPropertyDescriptor(object);
			addAutoGeneratedPropertyDescriptor(object);
			addRelatedHazardsPropertyDescriptor(object);
			addResponsiblePersonPropertyDescriptor(object);
			addDueDatePropertyDescriptor(object);
			addValidatesMechanismsPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Severity feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addSeverityPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_severity_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_severity_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__SEVERITY,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Occurrence feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addOccurrencePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_occurrence_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_occurrence_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__OCCURRENCE,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Detection feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addDetectionPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_detection_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_detection_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__DETECTION,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Local Effect feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addLocalEffectPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_localEffect_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_localEffect_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__LOCAL_EFFECT,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the System Effect feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addSystemEffectPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_systemEffect_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_systemEffect_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__SYSTEM_EFFECT,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Recommended Action feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addRecommendedActionPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_recommendedAction_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_recommendedAction_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__RECOMMENDED_ACTION,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Action Status feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addActionStatusPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_actionStatus_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_actionStatus_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__ACTION_STATUS,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Failure Mode feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addFailureModePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_failureMode_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_failureMode_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__FAILURE_MODE,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Analyzed Component feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnalyzedComponentPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_analyzedComponent_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_analyzedComponent_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__ANALYZED_COMPONENT,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Auto Generated feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAutoGeneratedPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_autoGenerated_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_autoGenerated_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__AUTO_GENERATED,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.BOOLEAN_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Related Hazards feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addRelatedHazardsPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_relatedHazards_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_relatedHazards_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__RELATED_HAZARDS,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Responsible Person feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addResponsiblePersonPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_responsiblePerson_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_responsiblePerson_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__RESPONSIBLE_PERSON,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Due Date feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addDueDatePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_dueDate_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_dueDate_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__DUE_DATE,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Validates Mechanisms feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addValidatesMechanismsPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_FMEAItem_validatesMechanisms_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_FMEAItem_validatesMechanisms_feature", "_UI_FMEAItem_type"),
				 UnifiedPackage.Literals.FMEA_ITEM__VALIDATES_MECHANISMS,
				 true,
				 false,
				 true,
				 null,
				 null,
				 null));
	}

	/**
	 * This returns FMEAItem.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/FMEAItem"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((FMEAItem)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_FMEAItem_type") :
			getString("_UI_FMEAItem_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(FMEAItem.class)) {
			case UnifiedPackage.FMEA_ITEM__SEVERITY:
			case UnifiedPackage.FMEA_ITEM__OCCURRENCE:
			case UnifiedPackage.FMEA_ITEM__DETECTION:
			case UnifiedPackage.FMEA_ITEM__LOCAL_EFFECT:
			case UnifiedPackage.FMEA_ITEM__SYSTEM_EFFECT:
			case UnifiedPackage.FMEA_ITEM__RECOMMENDED_ACTION:
			case UnifiedPackage.FMEA_ITEM__ACTION_STATUS:
			case UnifiedPackage.FMEA_ITEM__AUTO_GENERATED:
			case UnifiedPackage.FMEA_ITEM__RESPONSIBLE_PERSON:
			case UnifiedPackage.FMEA_ITEM__DUE_DATE:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);
	}

}
