/**
 */
package unified.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import unified.util.UnifiedAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UnifiedItemProviderAdapterFactory extends UnifiedAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UnifiedItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.UnifiedSystemModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnifiedSystemModelItemProvider unifiedSystemModelItemProvider;

	/**
	 * This creates an adapter for a {@link unified.UnifiedSystemModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnifiedSystemModelAdapter() {
		if (unifiedSystemModelItemProvider == null) {
			unifiedSystemModelItemProvider = new UnifiedSystemModelItemProvider(this);
		}

		return unifiedSystemModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.FMEAAnalysis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FMEAAnalysisItemProvider fmeaAnalysisItemProvider;

	/**
	 * This creates an adapter for a {@link unified.FMEAAnalysis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFMEAAnalysisAdapter() {
		if (fmeaAnalysisItemProvider == null) {
			fmeaAnalysisItemProvider = new FMEAAnalysisItemProvider(this);
		}

		return fmeaAnalysisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.FMEAItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FMEAItemItemProvider fmeaItemItemProvider;

	/**
	 * This creates an adapter for a {@link unified.FMEAItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFMEAItemAdapter() {
		if (fmeaItemItemProvider == null) {
			fmeaItemItemProvider = new FMEAItemItemProvider(this);
		}

		return fmeaItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.IntegratedHazard} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegratedHazardItemProvider integratedHazardItemProvider;

	/**
	 * This creates an adapter for a {@link unified.IntegratedHazard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegratedHazardAdapter() {
		if (integratedHazardItemProvider == null) {
			integratedHazardItemProvider = new IntegratedHazardItemProvider(this);
		}

		return integratedHazardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.SafetyCriticalBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SafetyCriticalBlockItemProvider safetyCriticalBlockItemProvider;

	/**
	 * This creates an adapter for a {@link unified.SafetyCriticalBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSafetyCriticalBlockAdapter() {
		if (safetyCriticalBlockItemProvider == null) {
			safetyCriticalBlockItemProvider = new SafetyCriticalBlockItemProvider(this);
		}

		return safetyCriticalBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.SystemBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemBlockItemProvider systemBlockItemProvider;

	/**
	 * This creates an adapter for a {@link unified.SystemBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemBlockAdapter() {
		if (systemBlockItemProvider == null) {
			systemBlockItemProvider = new SystemBlockItemProvider(this);
		}

		return systemBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.BlockAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockAssociationItemProvider blockAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link unified.BlockAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockAssociationAdapter() {
		if (blockAssociationItemProvider == null) {
			blockAssociationItemProvider = new BlockAssociationItemProvider(this);
		}

		return blockAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.BlockConnection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockConnectionItemProvider blockConnectionItemProvider;

	/**
	 * This creates an adapter for a {@link unified.BlockConnection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockConnectionAdapter() {
		if (blockConnectionItemProvider == null) {
			blockConnectionItemProvider = new BlockConnectionItemProvider(this);
		}

		return blockConnectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.BlockFailureMode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockFailureModeItemProvider blockFailureModeItemProvider;

	/**
	 * This creates an adapter for a {@link unified.BlockFailureMode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockFailureModeAdapter() {
		if (blockFailureModeItemProvider == null) {
			blockFailureModeItemProvider = new BlockFailureModeItemProvider(this);
		}

		return blockFailureModeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.AnalysisMetadata} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnalysisMetadataItemProvider analysisMetadataItemProvider;

	/**
	 * This creates an adapter for a {@link unified.AnalysisMetadata}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnalysisMetadataAdapter() {
		if (analysisMetadataItemProvider == null) {
			analysisMetadataItemProvider = new AnalysisMetadataItemProvider(this);
		}

		return analysisMetadataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.SafetyGoal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SafetyGoalItemProvider safetyGoalItemProvider;

	/**
	 * This creates an adapter for a {@link unified.SafetyGoal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSafetyGoalAdapter() {
		if (safetyGoalItemProvider == null) {
			safetyGoalItemProvider = new SafetyGoalItemProvider(this);
		}

		return safetyGoalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.FunctionalSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalSafetyRequirementItemProvider functionalSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link unified.FunctionalSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalSafetyRequirementAdapter() {
		if (functionalSafetyRequirementItemProvider == null) {
			functionalSafetyRequirementItemProvider = new FunctionalSafetyRequirementItemProvider(this);
		}

		return functionalSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.TechnicalSafetyRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnicalSafetyRequirementItemProvider technicalSafetyRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link unified.TechnicalSafetyRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnicalSafetyRequirementAdapter() {
		if (technicalSafetyRequirementItemProvider == null) {
			technicalSafetyRequirementItemProvider = new TechnicalSafetyRequirementItemProvider(this);
		}

		return technicalSafetyRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link unified.SafetyMechanism} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SafetyMechanismItemProvider safetyMechanismItemProvider;

	/**
	 * This creates an adapter for a {@link unified.SafetyMechanism}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSafetyMechanismAdapter() {
		if (safetyMechanismItemProvider == null) {
			safetyMechanismItemProvider = new SafetyMechanismItemProvider(this);
		}

		return safetyMechanismItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (unifiedSystemModelItemProvider != null) unifiedSystemModelItemProvider.dispose();
		if (fmeaAnalysisItemProvider != null) fmeaAnalysisItemProvider.dispose();
		if (fmeaItemItemProvider != null) fmeaItemItemProvider.dispose();
		if (integratedHazardItemProvider != null) integratedHazardItemProvider.dispose();
		if (safetyCriticalBlockItemProvider != null) safetyCriticalBlockItemProvider.dispose();
		if (systemBlockItemProvider != null) systemBlockItemProvider.dispose();
		if (blockAssociationItemProvider != null) blockAssociationItemProvider.dispose();
		if (blockConnectionItemProvider != null) blockConnectionItemProvider.dispose();
		if (blockFailureModeItemProvider != null) blockFailureModeItemProvider.dispose();
		if (analysisMetadataItemProvider != null) analysisMetadataItemProvider.dispose();
		if (safetyGoalItemProvider != null) safetyGoalItemProvider.dispose();
		if (functionalSafetyRequirementItemProvider != null) functionalSafetyRequirementItemProvider.dispose();
		if (technicalSafetyRequirementItemProvider != null) technicalSafetyRequirementItemProvider.dispose();
		if (safetyMechanismItemProvider != null) safetyMechanismItemProvider.dispose();
	}

}
