/**
 */
package unified;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FMEA Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link unified.FMEAItem#getSeverity <em>Severity</em>}</li>
 *   <li>{@link unified.FMEAItem#getOccurrence <em>Occurrence</em>}</li>
 *   <li>{@link unified.FMEAItem#getDetection <em>Detection</em>}</li>
 *   <li>{@link unified.FMEAItem#getLocalEffect <em>Local Effect</em>}</li>
 *   <li>{@link unified.FMEAItem#getSystemEffect <em>System Effect</em>}</li>
 *   <li>{@link unified.FMEAItem#getRecommendedAction <em>Recommended Action</em>}</li>
 *   <li>{@link unified.FMEAItem#getActionStatus <em>Action Status</em>}</li>
 *   <li>{@link unified.FMEAItem#getFailureMode <em>Failure Mode</em>}</li>
 *   <li>{@link unified.FMEAItem#getAnalyzedComponent <em>Analyzed Component</em>}</li>
 *   <li>{@link unified.FMEAItem#isAutoGenerated <em>Auto Generated</em>}</li>
 *   <li>{@link unified.FMEAItem#getRelatedHazards <em>Related Hazards</em>}</li>
 *   <li>{@link unified.FMEAItem#getResponsiblePerson <em>Responsible Person</em>}</li>
 *   <li>{@link unified.FMEAItem#getDueDate <em>Due Date</em>}</li>
 *   <li>{@link unified.FMEAItem#getValidatesMechanisms <em>Validates Mechanisms</em>}</li>
 * </ul>
 *
 * @see unified.UnifiedPackage#getFMEAItem()
 * @model
 * @generated
 */
public interface FMEAItem extends UnifiedElement {
	/**
	 * Returns the value of the '<em><b>Severity</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Severity</em>' attribute.
	 * @see #setSeverity(int)
	 * @see unified.UnifiedPackage#getFMEAItem_Severity()
	 * @model
	 * @generated
	 */
	int getSeverity();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getSeverity <em>Severity</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Severity</em>' attribute.
	 * @see #getSeverity()
	 * @generated
	 */
	void setSeverity(int value);

	/**
	 * Returns the value of the '<em><b>Occurrence</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Occurrence</em>' attribute.
	 * @see #setOccurrence(int)
	 * @see unified.UnifiedPackage#getFMEAItem_Occurrence()
	 * @model
	 * @generated
	 */
	int getOccurrence();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getOccurrence <em>Occurrence</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Occurrence</em>' attribute.
	 * @see #getOccurrence()
	 * @generated
	 */
	void setOccurrence(int value);

	/**
	 * Returns the value of the '<em><b>Detection</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Detection</em>' attribute.
	 * @see #setDetection(int)
	 * @see unified.UnifiedPackage#getFMEAItem_Detection()
	 * @model
	 * @generated
	 */
	int getDetection();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getDetection <em>Detection</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Detection</em>' attribute.
	 * @see #getDetection()
	 * @generated
	 */
	void setDetection(int value);

	/**
	 * Returns the value of the '<em><b>Local Effect</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Local Effect</em>' attribute.
	 * @see #setLocalEffect(String)
	 * @see unified.UnifiedPackage#getFMEAItem_LocalEffect()
	 * @model
	 * @generated
	 */
	String getLocalEffect();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getLocalEffect <em>Local Effect</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Local Effect</em>' attribute.
	 * @see #getLocalEffect()
	 * @generated
	 */
	void setLocalEffect(String value);

	/**
	 * Returns the value of the '<em><b>System Effect</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>System Effect</em>' attribute.
	 * @see #setSystemEffect(String)
	 * @see unified.UnifiedPackage#getFMEAItem_SystemEffect()
	 * @model
	 * @generated
	 */
	String getSystemEffect();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getSystemEffect <em>System Effect</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>System Effect</em>' attribute.
	 * @see #getSystemEffect()
	 * @generated
	 */
	void setSystemEffect(String value);

	/**
	 * Returns the value of the '<em><b>Recommended Action</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Recommended Action</em>' attribute.
	 * @see #setRecommendedAction(String)
	 * @see unified.UnifiedPackage#getFMEAItem_RecommendedAction()
	 * @model
	 * @generated
	 */
	String getRecommendedAction();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getRecommendedAction <em>Recommended Action</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Recommended Action</em>' attribute.
	 * @see #getRecommendedAction()
	 * @generated
	 */
	void setRecommendedAction(String value);

	/**
	 * Returns the value of the '<em><b>Action Status</b></em>' attribute.
	 * The literals are from the enumeration {@link unified.ActionStatus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Action Status</em>' attribute.
	 * @see unified.ActionStatus
	 * @see #setActionStatus(ActionStatus)
	 * @see unified.UnifiedPackage#getFMEAItem_ActionStatus()
	 * @model
	 * @generated
	 */
	ActionStatus getActionStatus();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getActionStatus <em>Action Status</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Action Status</em>' attribute.
	 * @see unified.ActionStatus
	 * @see #getActionStatus()
	 * @generated
	 */
	void setActionStatus(ActionStatus value);

	/**
	 * Returns the value of the '<em><b>Failure Mode</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Failure Mode</em>' reference.
	 * @see #setFailureMode(BlockFailureMode)
	 * @see unified.UnifiedPackage#getFMEAItem_FailureMode()
	 * @model
	 * @generated
	 */
	BlockFailureMode getFailureMode();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getFailureMode <em>Failure Mode</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Failure Mode</em>' reference.
	 * @see #getFailureMode()
	 * @generated
	 */
	void setFailureMode(BlockFailureMode value);

	/**
	 * Returns the value of the '<em><b>Analyzed Component</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Analyzed Component</em>' reference.
	 * @see #setAnalyzedComponent(SafetyCriticalBlock)
	 * @see unified.UnifiedPackage#getFMEAItem_AnalyzedComponent()
	 * @model required="true"
	 * @generated
	 */
	SafetyCriticalBlock getAnalyzedComponent();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getAnalyzedComponent <em>Analyzed Component</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Analyzed Component</em>' reference.
	 * @see #getAnalyzedComponent()
	 * @generated
	 */
	void setAnalyzedComponent(SafetyCriticalBlock value);

	/**
	 * Returns the value of the '<em><b>Auto Generated</b></em>' attribute.
	 * The default value is <code>"false"</code>.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Auto Generated</em>' attribute.
	 * @see #setAutoGenerated(boolean)
	 * @see unified.UnifiedPackage#getFMEAItem_AutoGenerated()
	 * @model default="false"
	 * @generated
	 */
	boolean isAutoGenerated();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#isAutoGenerated <em>Auto Generated</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Auto Generated</em>' attribute.
	 * @see #isAutoGenerated()
	 * @generated
	 */
	void setAutoGenerated(boolean value);

	/**
	 * Returns the value of the '<em><b>Related Hazards</b></em>' reference list.
	 * The list contents are of type {@link unified.IntegratedHazard}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Related Hazards</em>' reference list.
	 * @see unified.UnifiedPackage#getFMEAItem_RelatedHazards()
	 * @model
	 * @generated
	 */
	EList<IntegratedHazard> getRelatedHazards();

	/**
	 * Returns the value of the '<em><b>Responsible Person</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Responsible Person</em>' attribute.
	 * @see #setResponsiblePerson(String)
	 * @see unified.UnifiedPackage#getFMEAItem_ResponsiblePerson()
	 * @model
	 * @generated
	 */
	String getResponsiblePerson();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getResponsiblePerson <em>Responsible Person</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Responsible Person</em>' attribute.
	 * @see #getResponsiblePerson()
	 * @generated
	 */
	void setResponsiblePerson(String value);

	/**
	 * Returns the value of the '<em><b>Due Date</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Due Date</em>' attribute.
	 * @see #setDueDate(Date)
	 * @see unified.UnifiedPackage#getFMEAItem_DueDate()
	 * @model
	 * @generated
	 */
	Date getDueDate();

	/**
	 * Sets the value of the '{@link unified.FMEAItem#getDueDate <em>Due Date</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Due Date</em>' attribute.
	 * @see #getDueDate()
	 * @generated
	 */
	void setDueDate(Date value);

	/**
	 * Returns the value of the '<em><b>Validates Mechanisms</b></em>' reference list.
	 * The list contents are of type {@link unified.SafetyMechanism}.
	 * It is bidirectional and its opposite is '{@link unified.SafetyMechanism#getValidatedBy <em>Validated By</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Validates Mechanisms</em>' reference list.
	 * @see unified.UnifiedPackage#getFMEAItem_ValidatesMechanisms()
	 * @see unified.SafetyMechanism#getValidatedBy
	 * @model opposite="validatedBy"
	 * @generated
	 */
	EList<SafetyMechanism> getValidatesMechanisms();

} // FMEAItem
